In [5]:
import numpy as np

In [6]:
def pop_init(len_x, len_y, n_pop, n_exits):
    '''Initializing the population'''
    pop = np.zeros((len_x, len_y))
    coordinate = np.zeros((2))
    while np.count_nonzero(pop) < n_pop:
        print('hoi')
        coordinate[0] = np.random.randint(len_x, dtype=int)
        coordinate[1] = np.random.randint(len_y, dtype=int)
        pop[int(coordinate[0]), int(coordinate[1])] = np.random.randint(1, high=n_exits+1, dtype=int)
    return pop

matrix = pop_init(10, 10, 70, 2)
print(matrix)
print(np.count_nonzero(matrix))

0
30
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
0
